#include <stdio.h>
#include "arvore_binaria.h"

int main(){
    printf("Iniciando o Teste\n");
    printf("Construindos Arvores\n");
    ArvoreBinaria *ab = ab_cria();
    ArvoreBinaria *ab2 = ab_cria();
    ArvoreBinaria *ab3 = ab_cria();
    printf("Arvores esta vazia? %s\n", ab_vazia(ab)?"Sim":"Nao");
    printf("Criando um no e definindo como raiz\n");
    ab_define_raiz(ab, ab_cria_no("2", NULL, NULL));
    ab_define_raiz(ab2, ab_cria_no("2", NULL, NULL));
    ab_define_raiz(ab3, ab_cria_no("2", NULL, NULL));
    NoArvoreBinaria *ele1 = ab_cria_no("1", NULL, NULL);
    NoArvoreBinaria *ele4 = ab_cria_no("4", NULL, NULL);
    NoArvoreBinaria *ele6 = ab_cria_no("6", NULL, NULL);
    NoArvoreBinaria *ele5 = ab_cria_no("5", NULL, ele6);
    NoArvoreBinaria *ele3 = ab_cria_no("3", ele4, ele5);
    ab->raiz->sae = ele1;
    ab->raiz->sad = ele3;
    ab2->raiz->sae = ele1;
    ab2->raiz->sad = ele3;
    ab3->raiz->sad = ele1;
    ab3->raiz->sae = ele3;
    printf("Arvores esta vazia? %s\n", ab_vazia(ab)?"Sim":"Nao");
    printf("Entao me mostre os valores na maneira pre\n");
    ab_imprime_pre(ab);
    printf("Entao me mostre os valores na maneira sim\n");
    ab_imprime_sim(ab);
    printf("Entao me mostre os valores na maneira pos\n");
    ab_imprime_pos(ab);
    printf("Qual e a altura desta arvore? %d\n", ab_altura(ab));
    printf("Arvore 1 e 2 são iguais? %s\n", ab_igual(ab, ab2)?"Sim":"Nao");
    printf("Arvore 1 e 3 são iguais? %s\n", ab_igual(ab, ab3)?"Sim":"Nao");
    printf("O elemento 3 pertence a Arvore? %s\n", ab_pertence(ab,"3")?"Sim":"Nao");
    printf("Quantos nos a Arvore possui? %d\n", ab_num_nos(ab));
    printf("Destes nos, quantos sao folhas na Arvore? %d\n", ab_folhas(ab));
    printf("Vamos liberar a Arvore\n");
    ab_libera(ab);
    printf("Fim do Teste da Arvore\n");
    printf("\n\n===========================================\n\n");
    printf("Chaveamento da Copa do Mundo\n");
    ArvoreBinaria *cm = ab_cria();
    ab_define_raiz(cm, ab_cria_no("Final", NULL, NULL));
    NoArvoreBinaria *t1 = ab_cria_no("BRASIL", NULL, NULL);
    NoArvoreBinaria *t2 = ab_cria_no("ARGENTINA", NULL, NULL);
    NoArvoreBinaria *t3 = ab_cria_no("FRANCA", NULL, NULL);
    NoArvoreBinaria *t4 = ab_cria_no("ALEMANHA", NULL, NULL);
    NoArvoreBinaria *s1 = ab_cria_no("Semifinal 1", t1, t2);
    NoArvoreBinaria *s2 = ab_cria_no("Semifinal 2", t3, t4);
    cm->raiz->sae = s1;
    cm->raiz->sad = s2;
    printf("Chaveamento pre-ordem:\n");
    ab_imprime_pre(cm);
    printf("Chaveamento ordem simetrica:\n");
    ab_imprime_sim(cm);
    printf("Chaveamento pos-ordem:\n");
    ab_imprime_pos(cm);
    printf("Quantidade de partidas %d\n", ab_num_nos(cm)-ab_folhas(cm));
    printf("Quantidade de selecoes no chaveamento %d\n", ab_folhas(cm));
    printf("Qual altura da arvore? %d\n", ab_altura(cm));
    printf("A selecao do BRASIL esta no chaveamento? %s\n", ab_pertence(cm, "BRASIL")?"Sim":"Nao");
    ArvoreBinaria *cm2 = ab_cria();
    ab_define_raiz(cm2, ab_cria_no("Final", NULL, NULL));
    //NoArvoreBinaria *t12 = ab_cria_no("BRASIL", NULL, NULL);
    NoArvoreBinaria *t12 = ab_cria_no("URUGUAI", NULL, NULL);
    NoArvoreBinaria *t22 = ab_cria_no("ARGENTINA", NULL, NULL);
    NoArvoreBinaria *t32 = ab_cria_no("FRANCA", NULL, NULL);
    NoArvoreBinaria *t42 = ab_cria_no("ALEMANHA", NULL, NULL);
    NoArvoreBinaria *s12 = ab_cria_no("Semifinal 1", t12, t22);
    NoArvoreBinaria *s22 = ab_cria_no("Semifinal 2", t32, t42);
    cm2->raiz->sae = s12;
    cm2->raiz->sad = s22;
    printf("Os dois chaveamentos sao iguais? %s\n", ab_igual(cm, cm2)?"Sim":"Nao");
    return 0;
}