#include <stdio.h>
#include "arvore_naria.h"

int main() {
    printf("Iniciando o Teste\n");
    ArvoreNaria *a = an_cria();
    printf("Criando nos\n");
    NoArvoreNaria *n1  = an_cria_no("1");
    NoArvoreNaria *n2  = an_cria_no("2");
    NoArvoreNaria *n3  = an_cria_no("3");
    NoArvoreNaria *n4  = an_cria_no("4");
    NoArvoreNaria *n5  = an_cria_no("5");
    NoArvoreNaria *n6  = an_cria_no("6");
    NoArvoreNaria *n7  = an_cria_no("7");
    NoArvoreNaria *n8  = an_cria_no("8");
    NoArvoreNaria *n9  = an_cria_no("9");
    NoArvoreNaria *n10 = an_cria_no("10");
    printf("Definindo raiz\n");
    an_define_raiz(a, n1);
    printf("Inserindo filhos\n");
    an_insere_filho(n3, n4);
    an_insere_filho(n2, n5);
    an_insere_filho(n2, n3);
    an_insere_filho(n9, n10);
    an_insere_filho(n7, n9);
    an_insere_filho(n7, n8);
    an_insere_filho(n1, n7);
    an_insere_filho(n1, n6);
    an_insere_filho(n1, n2);
    printf("Arvore construida:\n");
    an_imprime(a);
    printf("Altura da arvore: %d\n", an_altura(a));
    printf("Numero de nos: %d\n", an_num_nos(a));
    printf("Numero de folhas: %d\n", an_folhas(a));
    printf("O elemento 9 pertence? %s\n", an_pertence(a, "9") ? "Sim" : "Nao");
    printf("O elemento 20 pertence? %s\n", an_pertence(a, "20") ? "Sim" : "Nao");
    printf("Criando segunda arvore para teste de igualdade\n");
    ArvoreNaria *a2 = an_cria();
    NoArvoreNaria *m1  = an_cria_no("1");
    NoArvoreNaria *m2  = an_cria_no("2");
    NoArvoreNaria *m3  = an_cria_no("3");
    NoArvoreNaria *m4  = an_cria_no("4");
    NoArvoreNaria *m5  = an_cria_no("5");
    NoArvoreNaria *m6  = an_cria_no("6");
    NoArvoreNaria *m7  = an_cria_no("7");
    NoArvoreNaria *m8  = an_cria_no("8");
    NoArvoreNaria *m9  = an_cria_no("9");
    NoArvoreNaria *m10 = an_cria_no("10");
    an_define_raiz(a2, m1);
    an_insere_filho(m3, m4);
    an_insere_filho(m2, m5);
    an_insere_filho(m2, m3);
    an_insere_filho(m9, m10);
    an_insere_filho(m7, m9);
    an_insere_filho(m7, m8);
    an_insere_filho(m1, m7);
    an_insere_filho(m1, m6);
    an_insere_filho(m1, m2);
    printf("As duas arvores sao iguais? %s\n", an_igual(a, a2) ? "Sim" : "Nao");
    printf("Alterando a segunda arvore\n");
    NoArvoreNaria *m11 = an_cria_no("11");
    an_insere_filho(m5, m11);
    printf("As duas arvores continuam iguais? %s\n", an_igual(a, a2) ? "Sim" : "Nao");
    printf("Liberandos arvores\n");
    an_libera(a);
    an_libera(a2);
    printf("Fim do Teste da Arvore\n");

    printf("\n\n===========================================\n\n");

    printf("Estrutura organizacional simplificada do Instituto Federal Catarinense\n");
    printf("Criando arvore\n");
    ArvoreNaria *o = an_cria();
    printf("Definindo sua raiz\n");
    NoArvoreNaria *ifc = an_cria_no("IFC");
    an_define_raiz(o, ifc);
    printf("Adicionado campi\n");
    NoArvoreNaria *blu = an_cria_no("Campus Blumenau");
    NoArvoreNaria *rs = an_cria_no("Campus Rio do Sul");
    NoArvoreNaria *ara = an_cria_no("Campus Araquari");
    printf("Adicionando Cursos\n");
    NoArvoreNaria *bcc = an_cria_no("BCC");
    NoArvoreNaria *ped = an_cria_no("Pedagogia");
    NoArvoreNaria *ene = an_cria_no("Engenharia Eletrica");
    printf("Adicionando Setores\n");
    NoArvoreNaria *cnp = an_cria_no("Coordenacao de Pesquisa");
    NoArvoreNaria *sia = an_cria_no("SISAE");
    NoArvoreNaria *aee = an_cria_no("AEE");
    printf("Adicionando Disciplinas\n");
    NoArvoreNaria *esd = an_cria_no("Estrutura de Dados I");
    NoArvoreNaria *poo2 = an_cria_no("POO2");
    NoArvoreNaria *fis = an_cria_no("Fisica I");
    printf("Definindo a estrutura da arvore\n");
    an_insere_filho(ifc, blu);
    an_insere_filho(ifc, rs);
    an_insere_filho(ifc, ara);
    an_insere_filho(blu, bcc);
    an_insere_filho(blu, ped);
    an_insere_filho(blu, ene);
    an_insere_filho(blu, cnp);
    an_insere_filho(blu, sia);
    an_insere_filho(blu, aee);
    an_insere_filho(bcc, esd);
    an_insere_filho(bcc, poo2);
    an_insere_filho(ene, fis);
    printf("Mostrando a hierarquia da arvore estrutural:\n");
    an_imprime(o);
    printf("Numero de nos: %d\n", an_num_nos(o));
    printf("Numero de folhas: %d\n", an_folhas(o));
    printf("Altura da arvore: %d\n", an_altura(o));
    printf("O curso Administracao pertence? %s\n", an_pertence(o, "Administracao") ? "Sim" : "Nao");
    printf("O setor SISAE pertence? %s\n", an_pertence(o, "SISAE") ? "Sim" : "Nao");
    printf("Criando segunda arvore organizacional para teste de igualdade\n");
    ArvoreNaria *o2 = an_cria();
    NoArvoreNaria *ifc2 = an_cria_no("IFC");
    an_define_raiz(o2, ifc2);
    NoArvoreNaria *blu2 = an_cria_no("Campus Blumenau");
    NoArvoreNaria *rs2  = an_cria_no("Campus Rio do Sul");
    NoArvoreNaria *ara2 = an_cria_no("Campus Araquari");
    NoArvoreNaria *bcc2 = an_cria_no("BCC");
    NoArvoreNaria *ped2 = an_cria_no("Pedagogia");
    NoArvoreNaria *ene2 = an_cria_no("Engenharia Eletrica");
    NoArvoreNaria *cnp2 = an_cria_no("Coordenacao de Pesquisa");
    NoArvoreNaria *sia2 = an_cria_no("SISAE");
    NoArvoreNaria *aee2 = an_cria_no("AEE");
    NoArvoreNaria *esd2  = an_cria_no("Estrutura de Dados I");
    NoArvoreNaria *poo22 = an_cria_no("POO2");
    NoArvoreNaria *fis2  = an_cria_no("Fisica I");
    an_insere_filho(ifc2, blu2);
    an_insere_filho(ifc2, rs2);
    an_insere_filho(ifc2, ara2);
    an_insere_filho(blu2, bcc2);
    an_insere_filho(blu2, ped2);
    an_insere_filho(blu2, ene2);
    an_insere_filho(blu2, cnp2);
    an_insere_filho(blu2, sia2);
    an_insere_filho(blu2, aee2);
    an_insere_filho(bcc2, esd2);
    an_insere_filho(bcc2, poo22);
    an_insere_filho(ene2, fis2);
    printf("As estruturas organizacionais sao iguais? %s\n", an_igual(o, o2) ? "Sim" : "Nao");
    printf("Alterando a segunda estrutura organizacional\n");
    NoArvoreNaria *adm2 = an_cria_no("Administracao");
    an_insere_filho(blu2, adm2);
    printf("As estruturas continuam iguais? %s\n", an_igual(o, o2) ? "Sim" : "Nao");
    printf("Liberando arvores organizacionais\n");
    an_libera(o2);
    an_libera(o);
    return 0;
}