#include <stdio.h>
#include "fila.h"

int main(){
    printf("Inicio do meu teste: \n");
    printf("Criando a fila: \n");
    Fila *f = fila_cria(4);
    printf("A fila esta vazia? %s\n", fila_vazia(f)?"Sim":"Nao");
    fila_enqueue(f, 3);
    fila_enqueue(f, 1);
    fila_enqueue(f, 2);
    fila_enqueue(f, 4);
    printf("A fila esta vazia? %s\n", fila_vazia(f)?"Sim":"Nao");
    printf("Imprimindo valores da fila: \n");
    fila_imprime(f);
    printf("O primeiro da fila vai sair, ele era o %d\n", fila_dequeue(f));
    printf("Imprimindo valores da fila: \n");
    fila_imprime(f);
    printf("Ja que um elemento saiu, vamos adicionar mais um\n");
    fila_enqueue(f,5);
    printf("Veja a lista\n");
    fila_imprime(f);
    Fila *f2 = fila_cria(6);
    fila_enqueue(f2, 3);
    fila_enqueue(f2, 8);
    fila_enqueue(f2, 10);
    fila_enqueue(f2, 9);
    printf("Realizando a concatenacao entre duas listas\n");
    Fila *f3 = fila_concatena(f, f2);
    printf("Mostrando os valores da concatenacao:\n");
    fila_imprime(f3);
    printf("Realizando o merge entre duas listas\n");
    Fila *f4 = fila_merge(f, f2);
    printf("Mostrando os valores do merge:\n");
    fila_imprime(f4);
    //printf("O que acontece se eu tentar inserir mais um elemento na lista?\n");
    //fila_enqueue(f, 6);
    printf("Reiniciando a fila\n");
    fila_reset(f); 
    printf("A fila esta vazia? %s\n", fila_vazia(f)?"Sim":"Nao");
    //printf("O que acontece se eu tentar remover um elemento da lista neste momento?\n");
    //fila_dequeue(f);  
    printf("Vamos liberar a lista\n");
    fila_libera(f);
    printf("Fim do meu teste\n");
    printf("\n================================================================\n\n");
    printf("Iniciando Problema Aplicado\n");
    printf("Capacidade da fila: %d\n", 5);
    Fila *filaAte = fila_cria(5);
    printf("Chegam as senhas: %d, %d, %d, %d, %d\n", 101, 102, 103, 104, 105);
    fila_enqueue(filaAte, 101);
    fila_enqueue(filaAte, 102);
    fila_enqueue(filaAte, 103);
    fila_enqueue(filaAte, 104);
    fila_enqueue(filaAte, 105);
    printf("Logo apos a senha 106 chega\n");
    fila_enqueue(filaAte, 106);
    printf("A fila esta cheia senhor, por favor espere\n");
    printf("Atende uma senha\n");
    fila_dequeue(filaAte);
    printf("A senha 106 pode vir!!\n");
    fila_enqueue(filaAte,106);
    printf("Exibe a fila atual\n");
    fila_imprime(filaAte);
    printf("Reinicia o atendimento\n");
    fila_reset(filaAte);
    printf("A fila de atendimento esta vazia? %s\n", fila_vazia?"Sim":"Nao");
    return 0;
}